# Generated by Django 3.2.18 on 2023-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='introduction',
            field=models.TextField(),
        ),
    ]
