# Generated by Django 3.2.18 on 2023-04-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_about_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(),
        ),
    ]
