# Generated by Django 4.2 on 2023-04-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_clients_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_img",
            field=models.ImageField(upload_to="static/clients_img"),
        ),
    ]
