# Generated by Django 4.2 on 2023-04-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_client_client_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_img",
            field=models.ImageField(upload_to="website/static/clients_img"),
        ),
    ]
