# Generated by Django 3.2.18 on 2023-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230424_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
