# Generated by Django 4.2 on 2023-04-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_client_client_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("happy_clinet", models.IntegerField()),
                ("working_hours", models.IntegerField()),
                ("awards_won", models.IntegerField()),
                ("coffee_consumed", models.IntegerField()),
            ],
        ),
    ]
