# Generated by Django 4.2 on 2023-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_fact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="awards_won",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="fact",
            name="coffee_consumed",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="fact",
            name="happy_clinet",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="fact",
            name="working_hours",
            field=models.CharField(max_length=30),
        ),
    ]
