# Generated by Django 4.2 on 2023-04-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="service_descriiption",
            new_name="service_description",
        ),
    ]
