# Generated by Django 4.2 on 2023-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_rename_service_descriiption_service_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_description",
            field=models.CharField(max_length=500),
        ),
    ]
