# Generated by Django 4.2 on 2023-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimonial_text", models.CharField(max_length=500)),
                (
                    "testimonial_picture",
                    models.ImageField(upload_to="website/static/testimonial_img"),
                ),
                ("testimonial_author", models.CharField(max_length=255)),
                ("testimonial_firm", models.CharField(max_length=255)),
            ],
        ),
    ]
