# Generated by Django 4.2 on 2023-04-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certi_logo", models.ImageField(upload_to="website/static/certi_img")),
                ("certi_title", models.CharField(max_length=255)),
                ("certi_id", models.CharField(max_length=255)),
                ("certi_date", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CodingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=255)),
                ("skill_precntage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=255)),
                ("university_year", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                ("major_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_description", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("start_date", models.CharField(max_length=255)),
                ("end_date", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=255)),
                ("skill_precntage", models.IntegerField()),
            ],
        ),
    ]
