# Generated by Django 4.2 on 2023-04-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.category"
            ),
        ),
    ]
