# Generated by Django 4.2 on 2023-04-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_categoryblog_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
