# Generated by Django 4.2 on 2023-04-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificates",
            name="certi_logo",
            field=models.ImageField(upload_to="static/certi_img"),
        ),
    ]
