# Generated by Django 4.2 on 2023-04-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_alter_certificates_certi_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_img",
            field=models.ImageField(upload_to="static/blog_img"),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_img",
            field=models.ImageField(upload_to="static/clients_img"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="project_image",
            field=models.ImageField(null=True, upload_to="static/project_img"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="testimonial_picture",
            field=models.ImageField(upload_to="static/testimonial_img"),
        ),
    ]
