# Generated by Django 4.2 on 2023-04-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_alter_blog_blog_img_alter_client_client_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificates",
            name="certi_logo",
            field=models.ImageField(upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_img",
            field=models.ImageField(upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="testimonial_picture",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
