# Generated by Django 4.2 on 2023-04-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_alter_certificates_certi_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_img",
            field=models.ImageField(upload_to="client/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="testimonial_picture",
            field=models.ImageField(upload_to="testimo/"),
        ),
    ]
