# Generated by Django 4.2 on 2023-04-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_alter_client_client_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_image",
            field=models.ImageField(null=True, upload_to="project"),
        ),
    ]
