# Generated by Django 4.2 on 2023-04-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_alter_portfolio_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_img",
            field=models.ImageField(upload_to="blog/"),
        ),
    ]
